### ISSUE TITLE
FEATURE: Upvote Downvote logic

### ISSUE THREAD

**Issue by lancenonce** [seree-fam/akoben#8]
## Is your feature request related to a problem? Please describe.

Currently, the upvote / downvote logic doesn't work for the forum. Posts with the most upvotes should bubble to the top, and vice versa for downvotes.

## Describe the solution you'd like

Basic upvote downvote logic.

## Describe alternatives you've considered

n/a

## Screenshots

<img width="815" alt="Screenshot 2024-07-01 at 9 10 26 AM" src="https://github.com/seree-fam/akoben/assets/40670744/8d3f6b9c-e50f-48cf-b4dd-63e74274fe0e">
The `Voting Challenges` Post should be at the top.

## Importance
- [x] **High** 
- [ ] **Medium**
- [ ] **Low**

**Comment by surfiniaburger** [comment]
![Screenshot (400)](https://github.com/seree-fam/akoben/assets/102007621/7618b2aa-769b-4e2b-83e5-61e3a810765d)
